# For more information on configuration, see:
#   * Official English Documentation: http://nginx.org/en/docs/
#   * Official Russian Documentation: http://nginx.org/ru/docs/


worker_processes auto;
error_log /logs/${KUBERNETES_POD_NAME}/${KUBERNETES_NAMESPACE}__${ALERT_PROJECT_CODE}__${KUBERNETES_POD_NAME}-nginx-error.log warn;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    perl_set $request_time_ms 'sub {
        my $r = shift;
        my $request_time = $r->variable("request_time");
        return int($request_time*1000);
    }';

    log_format json_combined escape=json
      '{'
          '"x_forwarded_for":"$http_x_forwarded_for",'
          '"client_ip":"$remote_addr",'
          '"client_user":"$remote_user",'
          '"authenticated":"-",'
          '"request_time":"$time_iso8601",'
          '"request_url":"$request",'
          '"http_code":"$status",'
          '"send_bytes":"$body_bytes_sent",'
          '"query_string":"-",'
          '"http_referer":"$http_referer",'
          '"user_agent":"$http_user_agent",'
          '"request_time_ms":"$request_time_ms"'
      '}';

    access_log /logs/${KUBERNETES_POD_NAME}/${KUBERNETES_NAMESPACE}__${ALERT_PROJECT_CODE}__${KUBERNETES_POD_NAME}-nginx-access.log json_combined;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 4096;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /opt/app-root/etc/nginx.d/*.conf;

    server {
        listen       8080 default_server;
        server_name  _;
        root         /opt/app-root/src;

        # Load configuration files for the default server block.
        include /opt/app-root/etc/nginx.default.d/*.conf;
    }
}
