location /config/ {
    alias /app/config/;
    add_header Access-Control-Allow-Origin *;
    expires off;
    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
}

location = /version.json {
    access_log off;
    return 200 '{ "version": "${PLACEHOLDER_APP_VERSION}" }';
    add_header Content-Type "application/json" always;
    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    add_header Access-Control-Allow-Origin *;
    expires off;
}

location / {
    root /app/html/;
    try_files $uri $uri/ /index.html;
    add_header Access-Control-Allow-Origin *;

    if ($request_method = "OPTIONS") {
        add_header Access-Control-Allow-Origin $http_origin;
        add_header Access-Control-Allow-Methods *;
        add_header Access-Control-Allow-Headers *;
        add_header Content-Type text/plain;
        add_header Content-Length 0;
        return 204;
    }

    if ( $uri = "/index.html" ) {
        expires off;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }

    location ~ remoteEntry.js$ {
        expires off;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }
}

location /healthcheck { 
    access_log off; add_header "Content-Type" "text/plain"; return 200 "healthy\n";
}