-- DROP FUNCTION "fn_tI_User_profile"();

CREATE OR REPLACE FUNCTION "fn_tI_User_profile"()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
/* 20161212: enable Logging feature */
/* INSERT trigger on User_profile */
DECLARE
    var_numrows INTEGER;
    var_nullcnt INTEGER;
    var_validcnt INTEGER;
    var_hosp_code CHAR(3);
    var_start_dtm TIMESTAMP WITHOUT TIME ZONE;
    var_input_parm1 VARCHAR(255);
    /* Org Value */
    var_output_parm1 VARCHAR(255);
    /* New Value */
    var_user_id VARCHAR(12);
    var_term_id VARCHAR(12);
    var_monitor_type CHAR(3);
    var_rowcount$aws$ INTEGER;
    update$Group_ID BOOLEAN = FALSE;
BEGIN
    <<error>>
    BEGIN
        CASE TG_OP
            WHEN 'INSERT' THEN
                update$Group_ID = TRUE;
            WHEN 'UPDATE' THEN
                update$Group_ID = ((SELECT
                    array_agg(Group_ID)
                    FROM deleted) != (SELECT
                    array_agg(Group_ID)
                    FROM inserted));
            ELSE
                update$Group_ID := FALSE;
        END CASE;

        IF (TG_OP = 'INSERT') THEN
            SELECT
                count(1)
                FROM inserted
                INTO var_rowcount$aws$;
        ELSE
            SELECT
                count(1)
                FROM deleted
                INTO var_rowcount$aws$;
        END IF;
        /* INS/UPD */
        var_numrows := var_rowcount$aws$;

        IF var_numrows = 0 THEN
            RETURN NULL;
        END IF;
        /* User_group join with User_profile ON CHILD INSERT RESTRICT */
        IF update$Group_ID THEN
            BEGIN
                SELECT
                    0
                    INTO var_nullcnt;
                SELECT
                    COUNT(*)
                    INTO var_validcnt
                    FROM inserted, "User_group"
                    WHERE inserted."Group_ID" = "User_group"."Group_ID";
                /* and inserted.Hospital_code = User_group.Hospital_code   -- HPI */
                IF var_validcnt + var_nullcnt != var_numrows THEN
                    BEGIN
                        RAISE EXCEPTION '% % % ', 'INSERT', 'User_profile', 'User_group' USING ERRCODE = '200012';
                        EXIT error;
                    END;
                END IF;
            END;
        END IF;
        /* ------------------------------------------------------------------------------ */
        /* 20161215 : new records <pas_sys_perf_log>  with monitor_type='USER_PROF' -- */
        /* insert pas_monitor values('IPAS','USER_PROF','20161215','Records generated by User_profile Ins/Upd trigger',null,@hosp_code,null,null,null,'IPAS','ADT',getdate()) */
        /* ------------------------------------------------------------------------------ */
        SELECT
            "Hospital_code"
            INTO var_hosp_code
            FROM "Hospital";
        SELECT
            current_user
            INTO var_user_id;
        SELECT
            aws_sapase_ext.host_name()
            INTO var_term_id;
        SELECT
            'INS'
            INTO var_monitor_type;
        SELECT
            NULL
            INTO var_input_parm1;
        SELECT
            timestamp_convert(localtimestamp)
            INTO var_start_dtm;
        SELECT
            CONCAT(aws_sapase_ext.user_id, ':', inserted."Group_ID", ':', inserted."Password", ':', inserted."Department", ':', inserted."Name", ':', CAST (inserted."Authority_code" AS CHAR(12)), ':', to_char(inserted."Expiration_date"::TIMESTAMP WITHOUT TIME ZONE, 'YYYYMMDD'), ':', to_char(inserted."Effective_date"::TIMESTAMP WITHOUT TIME ZONE, 'YYYYMMDD'), ':', inserted."Rank_code", ':', inserted."Menu", ':', CAST (inserted."DT_security_code" AS CHAR(12)), ':', inserted."Hospital_code", ':', inserted."HKID", ':', inserted."User_title", ':', inserted."DT_enable_flag", ':', to_char(inserted."DT_effective_date"::TIMESTAMP WITHOUT TIME ZONE, 'YYYYMMDD'), ':', to_char(inserted."DT_expiration_date"::TIMESTAMP WITHOUT TIME ZONE, 'YYYYMMDD'), ':', to_char(inserted."Password_expiration_date"::TIMESTAMP WITHOUT TIME ZONE, 'YYYYMMDD'), ':', CAST (inserted."Password_retry_count" AS CHAR(12)), ':', inserted.cuid_flag)
            INTO var_output_parm1
            FROM inserted;
        /* --exec cpi..pas_ins_perf_log @hosp_code, 'IPAS', 'USER_PROF', @monitor_type, null,null,@user_id, @term_id, @start_dtm,null, -- CPI */
        CALL pas_ins_perf_log(pas_return_code, var_hosp_code, 'IPAS', 'USER_PROF', var_monitor_type, NULL, NULL, var_user_id, var_term_id, var_start_dtm, NULL, NULL, NULL, NULL, var_input_parm1, NULL, NULL, var_output_parm1, NULL);
        /* ------------------------------------------------------------------------------ */
        RETURN NULL;
    END;
    ROLLBACK;
    RETURN NULL;
END;
$function$
;

;ALTER FUNCTION "fn_tI_User_profile" OWNER TO "HPI_SCHEMA_OWNER_ROLE";
