-- transaction_log_mandatory definition

-- Drop table

-- DROP TABLE transaction_log_mandatory;

CREATE TABLE transaction_log_mandatory (
	transaction_type varchar(6) NOT NULL,
	system_dtm varchar(2) NOT NULL,
	hospital_code varchar(2) NOT NULL,
	"type" varchar(2) NOT NULL,
	adm_dtm varchar(2) NOT NULL,
	hkid varchar(2) NOT NULL,
	patient_key varchar(2) NOT NULL,
	patient_name varchar(2) NOT NULL,
	sex varchar(2) NOT NULL,
	dob varchar(2) NOT NULL,
	exact_dob_flag varchar(2) NOT NULL,
	cccode1 varchar(2) NOT NULL,
	cccode2 varchar(2) NOT NULL,
	cccode3 varchar(2) NOT NULL,
	cccode4 varchar(2) NOT NULL,
	cccode5 varchar(2) NOT NULL,
	cccode6 varchar(2) NOT NULL,
	chi_name varchar(2) NOT NULL,
	marital_status varchar(2) NOT NULL,
	race varchar(2) NOT NULL,
	other_doc_no varchar(2) NOT NULL,
	mrn varchar(2) NOT NULL,
	building varchar(2) NOT NULL,
	room varchar(2) NOT NULL,
	floor varchar(2) NOT NULL,
	block varchar(2) NOT NULL,
	district varchar(2) NOT NULL,
	religion varchar(2) NOT NULL,
	home_phone varchar(2) NOT NULL,
	office_phone varchar(2) NOT NULL,
	office_phone_ext varchar(2) NOT NULL,
	other_phone varchar(2) NOT NULL,
	other_phone_ext varchar(2) NOT NULL,
	death_indicator varchar(2) NOT NULL,
	death_date varchar(2) NOT NULL,
	death_external_cause varchar(2) NOT NULL,
	death_diagnosis varchar(2) NOT NULL,
	pcs_count varchar(2) NOT NULL,
	priority varchar(2) NOT NULL,
	major_nok varchar(2) NOT NULL,
	nok_name varchar(2) NOT NULL,
	nok_hkid varchar(2) NOT NULL,
	nok_relationship varchar(2) NOT NULL,
	nok_building varchar(2) NOT NULL,
	nok_room varchar(2) NOT NULL,
	nok_floor varchar(2) NOT NULL,
	nok_block varchar(2) NOT NULL,
	nok_district varchar(2) NOT NULL,
	nok_home_phone varchar(2) NOT NULL,
	nok_office_phone varchar(2) NOT NULL,
	nok_office_phone_ext varchar(2) NOT NULL,
	nok_other_phone varchar(2) NOT NULL,
	nok_other_phone_ext varchar(2) NOT NULL,
	case_no varchar(2) NOT NULL,
	source_indicator varchar(2) NOT NULL,
	source_code varchar(2) NOT NULL,
	patient_type varchar(2) NOT NULL,
	discharge_code varchar(2) NOT NULL,
	destination_code varchar(2) NOT NULL,
	case_type varchar(2) NOT NULL,
	security_count varchar(2) NOT NULL,
	case_access_code varchar(2) NOT NULL,
	pmi_access_code varchar(2) NOT NULL,
	ambulance_no varchar(2) NOT NULL,
	police_case varchar(2) NOT NULL,
	labour_case varchar(2) NOT NULL,
	ae_case_type varchar(2) NOT NULL,
	dba varchar(2) NOT NULL,
	ward_code varchar(2) NOT NULL,
	specialty_code varchar(2) NOT NULL,
	bed_no varchar(2) NOT NULL,
	ward_class varchar(2) NOT NULL,
	old_patient_key varchar(2) NOT NULL,
	old_patient_name varchar(2) NOT NULL,
	old_hkid varchar(2) NOT NULL,
	old_sex varchar(2) NOT NULL,
	old_dob varchar(2) NOT NULL,
	old_ward_class varchar(2) NOT NULL,
	old_ward_code varchar(2) NOT NULL,
	old_specialty_code varchar(2) NOT NULL,
	old_bed_no varchar(2) NOT NULL,
	pp_code varchar(2) NOT NULL,
	update_by varchar(2) NOT NULL,
	update_hospital varchar(2) NOT NULL,
	source_system varchar(2) NOT NULL,
	source_system_dtm varchar(2) NOT NULL,
	upload_status varchar(2) NOT NULL,
	filler varchar(2) NOT NULL,
	"timestamp" varchar(2) NOT NULL,
	doctor_code varchar(2) NOT NULL,
	mrt_indicator varchar(2) NOT NULL,
	transfer_dtm varchar(2) NOT NULL,
	discharge_dtm varchar(2) NOT NULL,
	patient_remove_flag varchar(2) NOT NULL,
	exact_death_date varchar(2) NOT NULL,
	document_flag varchar(2) NOT NULL,
	elderly_home_code varchar(2) NOT NULL,
	linked_hospital_code varchar(2) NOT NULL,
	linked_case_no varchar(2) NOT NULL,
	mother_hospital_code varchar(2) NOT NULL,
	baby_hospital_code varchar(2) NOT NULL,
	baby_case_no varchar(2) NOT NULL,
	update_type varchar(6) NULL,
	hkic_symbol varchar(2) NULL,
	last_update_datetime timestamp(6) NULL
);

CREATE UNIQUE INDEX "XPKtransaction_log_mandatory" ON transaction_log_mandatory USING btree (transaction_type);

ALTER TABLE transaction_log_mandatory OWNER TO "DOWNLOAD_SCHEMA_OWNER_ROLE";
