-- cpi_transaction definition

-- Drop table

-- DROP TABLE cpi_transaction;

CREATE TABLE cpi_transaction (
	hospital_code varchar(6) NOT NULL,
	transaction_datetime timestamp(6) NOT NULL,
	transaction_type varchar(6) NOT NULL,
	hkid varchar(24) NULL,
	patient_key varchar(16) NULL,
	patient_name varchar(96) NULL,
	sex varchar(2) NULL,
	dob timestamp(6) NULL,
	exact_dob_flag varchar(2) NULL,
	ccc_1 varchar(10) NULL,
	ccc_2 varchar(10) NULL,
	ccc_3 varchar(10) NULL,
	ccc_4 varchar(10) NULL,
	ccc_5 varchar(10) NULL,
	ccc_6 varchar(10) NULL,
	chi_name varchar(24) NULL,
	marital_status varchar(2) NULL,
	race_code varchar(4) NULL,
	other_document_no varchar(24) NULL,
	reference varchar(40) NULL,
	medical_record_number varchar(16) NULL,
	remark varchar(510) NULL,
	building varchar(94) NULL,
	room varchar(10) NULL,
	floor varchar(4) NULL,
	block varchar(4) NULL,
	district_code varchar(10) NULL,
	religion_code varchar(6) NULL,
	phone1 varchar(20) NULL,
	phone2 varchar(20) NULL,
	address_indicator varchar(8) NULL,
	mobile_phone varchar(20) NULL,
	sms_language varchar(8) NULL,
	death_indicator varchar(2) NULL,
	death_date timestamp(6) NULL,
	death_code varchar(8) NULL,
	card_holder int4 NULL,
	priority int4 NULL,
	major_nok varchar(2) NULL,
	nok_name varchar(96) NULL,
	nok_hkid varchar(24) NULL,
	nok_relation_code varchar(4) NULL,
	nok_building varchar(94) NULL,
	nok_room varchar(10) NULL,
	nok_floor varchar(4) NULL,
	nok_block varchar(4) NULL,
	nok_district_code varchar(10) NULL,
	nok_phone1 varchar(20) NULL,
	nok_phone2 varchar(20) NULL,
	nok_address_indicator varchar(8) NULL,
	nok_mobile_phone varchar(20) NULL,
	nok_sms_language varchar(8) NULL,
	case_no varchar(24) NULL,
	admission_datetime timestamp(6) NULL,
	source_indicator varchar(2) NULL,
	source_code varchar(6) NULL,
	patient_type varchar(6) NULL,
	discharge_code varchar(2) NULL,
	discharge_datetime timestamp(6) NULL,
	destination_code varchar(6) NULL,
	doctor_code varchar(16) NULL,
	case_type varchar(2) NULL,
	security_count int4 NULL,
	case_access_code int4 NULL,
	pmi_access_code int4 NULL,
	ambulance_no varchar(8) NULL,
	police_case varchar(2) NULL,
	labour_case varchar(2) NULL,
	ae_case_type varchar(2) NULL,
	dba_flag varchar(2) NULL,
	follow_up_datetime timestamp(6) NULL,
	ward_code varchar(8) NULL,
	specialty_code varchar(8) NULL,
	sub_specialty_code varchar(8) NULL,
	bed_no varchar(10) NULL,
	ward_class varchar(2) NULL,
	transfer_datetime timestamp(6) NULL,
	old_patient_key varchar(16) NULL,
	old_name varchar(96) NULL,
	old_hkid varchar(24) NULL,
	old_sex varchar(2) NULL,
	old_dob timestamp(6) NULL,
	old_ward_class varchar(2) NULL,
	old_ward_code varchar(8) NULL,
	old_specialty_code varchar(8) NULL,
	old_bed_no varchar(10) NULL,
	old_doctor_code varchar(16) NULL,
	pp_code varchar(16) NULL,
	update_hospital varchar(6) NOT NULL,
	update_by varchar(24) NOT NULL,
	update_datetime timestamp(6) NOT NULL,
	source_system varchar(10) NOT NULL,
	success_indicator varchar(2) NOT NULL,
	upload_status varchar(2) NOT NULL,
	source_system_dtm timestamp(6) NULL,
	cpi_filler varchar(60) NULL
);
CREATE UNIQUE INDEX cpi_transaction_idx ON cpi_transaction USING btree (hospital_code, transaction_datetime);
CREATE INDEX cpi_txn_upload_idx ON cpi_transaction USING btree (upload_status, transaction_datetime);




ALTER TABLE cpi_transaction OWNER TO "HPI_SCHEMA_OWNER_ROLE";
