-- event_log definition

-- Drop table

-- DROP TABLE event_log;

CREATE TABLE event_log (
	hospital_code varchar(6) NOT NULL,
	system_datetime timestamp(6) NOT NULL,
	"type" varchar(6) NOT NULL,
	hkid varchar(24) NOT NULL,
	"name" varchar(96) NULL,
	sex varchar(2) NULL,
	dob timestamp(6) NULL,
	exact_dob_flag varchar(2) NULL,
	ccc_1 varchar(10) NULL,
	ccc_2 varchar(10) NULL,
	ccc_3 varchar(10) NULL,
	ccc_4 varchar(10) NULL,
	ccc_5 varchar(10) NULL,
	ccc_6 varchar(10) NULL,
	martial_status varchar(2) NULL,
	race_code varchar(4) NULL,
	other_document_no varchar(24) NULL,
	medical_record_number varchar(16) NULL,
	building varchar(94) NULL,
	room varchar(10) NULL,
	floor varchar(4) NULL,
	block varchar(4) NULL,
	district_code varchar(10) NULL,
	religion_code varchar(6) NULL,
	phone1 varchar(20) NULL,
	phone2 varchar(20) NULL,
	address_indicator varchar(8) NULL,
	mobile_phone varchar(20) NULL,
	sms_language varchar(8) NULL,
	death_indicator varchar(2) NULL,
	death_date timestamp(6) NULL,
	t_prk varchar(16) NULL,
	nok_name varchar(96) NULL,
	nok_hkid varchar(24) NULL,
	nok_relation_code varchar(4) NULL,
	nok_building varchar(94) NULL,
	nok_room varchar(10) NULL,
	nok_floor varchar(4) NULL,
	nok_block varchar(4) NULL,
	nok_district_code varchar(10) NULL,
	nok_phone1 varchar(20) NULL,
	nok_phone2 varchar(20) NULL,
	nok_address_indicator varchar(8) NULL,
	nok_mobile_phone varchar(20) NULL,
	nok_sms_language varchar(8) NULL,
	case_no varchar(24) NULL,
	admission_datetime timestamp(6) NULL,
	source_indicator varchar(2) NULL,
	source_code varchar(6) NULL,
	pay_code varchar(6) NULL,
	discharge_code varchar(2) NULL,
	discharge_datetime timestamp(6) NULL,
	destination_code varchar(6) NULL,
	case_type varchar(2) NULL,
	movement_count int4 NULL,
	security_count int4 NULL,
	case_access_code int4 NULL,
	pmi_access_code int4 NULL,
	ambulance_no varchar(8) NULL,
	police_case varchar(2) NULL,
	labour_case varchar(2) NULL,
	ae_case_type varchar(2) NULL,
	dba_flag varchar(2) NULL,
	follow_up_datetime timestamp(6) NULL,
	from_ward_code varchar(8) NULL,
	from_specialty_code varchar(8) NULL,
	from_bed_no varchar(10) NULL,
	from_ward_class varchar(2) NULL,
	ward_code varchar(8) NULL,
	specialty_code varchar(8) NULL,
	bed_no varchar(10) NULL,
	ward_class varchar(2) NULL,
	old_name varchar(96) NULL,
	old_hkid varchar(24) NULL,
	old_sex varchar(2) NULL,
	old_dob timestamp(6) NULL,
	old_ward_class varchar(2) NULL,
	old_ward_code varchar(8) NULL,
	old_specialty_code varchar(8) NULL,
	old_bed_no varchar(10) NULL,
	user_id varchar(16) NOT NULL,
	upload_status varchar(2) NOT NULL,
	doctor_code varchar(16) NULL,
	old_doctor_code varchar(16) NULL,
	old_t_prk varchar(16) NULL,
	mrt_indicator varchar(2) NULL,
	last_update_datetime timestamp(6) NULL
);
CREATE UNIQUE INDEX "XIE1Event_log" ON event_log USING btree (hospital_code, system_datetime);
CREATE INDEX "XPKEvent_log" ON event_log USING btree (hospital_code, upload_status, system_datetime);
CREATE INDEX idx1_event_log ON event_log USING btree (case_no, system_datetime, type);



ALTER TABLE event_log OWNER TO "HPI_SCHEMA_OWNER_ROLE";
