-- upload definition

-- Drop table

-- DROP TABLE upload;

CREATE TABLE upload (
	hospital_code varchar(6) NOT NULL,
	case_no varchar(24) NOT NULL,
	hkid varchar(24) NOT NULL,
	"name" varchar(96) NOT NULL,
	sex varchar(2) NOT NULL,
	dob timestamp(6) NULL,
	marital_status varchar(2) NULL,
	pay_code varchar(6) NOT NULL,
	race_code varchar(4) NULL,
	specialty_code varchar(8) NULL,
	ward_code varchar(8) NULL,
	source_indicator varchar(2) NULL,
	source_code varchar(6) NULL,
	building varchar(94) NULL,
	room varchar(10) NULL,
	floor varchar(4) NULL,
	block varchar(4) NULL,
	district_code varchar(10) NULL,
	home_phone varchar(20) NULL,
	nok_name varchar(96) NULL,
	nok_hkid varchar(24) NULL,
	nok_relation_code varchar(4) NULL,
	nok_building varchar(94) NULL,
	nok_room varchar(10) NULL,
	nok_floor varchar(4) NULL,
	nok_block varchar(4) NULL,
	nok_district_code varchar(10) NULL,
	nok_home_phone varchar(20) NULL,
	nok_other_phone1 varchar(20) NULL,
	nok_other_ext1 varchar(8) NULL,
	admission_datetime timestamp(6) NULL,
	ae_case_type varchar(2) NULL,
	labour_case_flag varchar(2) NULL,
	ambulance_no varchar(8) NULL,
	police_case varchar(2) NULL,
	ccc_1 varchar(10) NULL,
	ccc_2 varchar(10) NULL,
	ccc_3 varchar(10) NULL,
	ccc_4 varchar(10) NULL,
	ccc_5 varchar(10) NULL,
	ccc_6 varchar(10) NULL,
	medical_record_number varchar(16) NULL,
	ward_class varchar(2) NULL,
	temp_ward varchar(8) NULL,
	other_document_no varchar(24) NULL,
	religion_code varchar(6) NULL,
	error_code varchar(8) NULL,
	op_flag varchar(10) NULL,
	diagnosis varchar(30) NULL,
	exact_dob_flag varchar(2) NOT NULL,
	message varchar(510) NULL,
	tx_datetime timestamp(6) NOT NULL,
	user_id varchar(16) NOT NULL,
	document_flag varchar(2) NULL,
	eh_code varchar(16) NULL,
	pp_code varchar(16) NULL,
	payment_amount int4 NULL,
	paid_amount int4 NULL,
	no_charge_indicator varchar(10) NULL,
	payment_means varchar(10) NULL,
	waiver_no varchar(48) NULL,
	waiver_effective_date timestamp(6) NULL,
	waiver_expiry_date timestamp(6) NULL,
	waiver_type varchar(2) NULL,
	waiver_issue_party varchar(8) NULL,
	workstation_id varchar(24) NULL,
	transaction_type varchar(2) NULL,
	remark varchar(96) NULL,
	previous_hospital varchar(6) NULL,
	previous_case varchar(24) NULL,
	nep_search_key varchar(40) NULL,
	nep_add_key_1 varchar(40) NULL,
	nep_add_key_2 varchar(40) NULL,
	hkic_symbol varchar(2) NULL,
	office_phone varchar(20) NULL,
	office_phone_ext varchar(8) NULL,
	other_phone varchar(20) NULL,
	other_phone_ext varchar(8) NULL,
	last_update_datetime timestamp(6) NULL,
	CONSTRAINT "XPKUpload" PRIMARY KEY (hospital_code, case_no, hkid) DEFERRABLE INITIALLY DEFERRED
);




ALTER TABLE upload OWNER TO "HPI_SCHEMA_OWNER_ROLE";
